### ISSUE TITLE
Review Kaban Board

### ISSUE THREAD

**Issue by tiagomarin** [tiagomarin/Best-Recepies#10]
I'm alone this week :man:  since they couldn't pair me up with anyone. I'm ok with that :smile: , in fact I've already started working on it :hammer_and_wrench: .

<img src="https://user-images.githubusercontent.com/99205303/203350762-d87973bb-7780-4e8a-a36f-73f0d97009fc.png" width=600>

I didn't put that much effort in the Kanban Board since I'll be the only one using, but I organized the tasks I'll be doing quite well I guess.

Please let me know if there's room for improvement, but bear in mind I'm alone.

[Kanban Board Link](https://github.com/users/tiagomarin/projects/12)

Thanks in advance. :wave:

**Comment by mukhammadrizooff** [comment]
Hi @tiagomarin, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Good implementations ✔️  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
